name: Test
on: [push, pull_request]
jobs:
  build:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "./test"
          secrets: fakesecrets.yaml
          version: stable
